#Task 1 :Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library).

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
inputs = np.array([[73, 67, 43],
                    [91, 88, 64],
                    [87, 134, 58],
                    [102, 43, 37],
                    [69, 96, 70],
                    [73, 67, 43],
                    [91, 88, 64],
                    [87, 134, 58],
                    [102, 43, 37],
                    [69, 96, 70],
                    [73, 67, 43], 
                    [91, 88, 64], 
                    [87, 134, 58], 
                    [102, 43, 37], 
                    [69, 96, 70]], dtype='float32')
print(inputs.shape)

(15, 3)


In [4]:
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(inputs,targets,test_size=0.3, random_state=130)

In [17]:
reg = LinearRegression().fit(x_train,y_train)
print(reg)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)


In [18]:
print(reg.intercept_)
print(reg.coef_)

[-3.2528687 -2.1050262]
[[-0.36699685  0.85361826  0.68239784]
 [-0.28660074  0.79359555  0.9260817 ]]


In [19]:
y_pred = reg.predict(x_test)
print(y_pred,"\n")
print(y_test)

[[ 82.14229  100.919945]
 [101.13956  119.13042 ]
 [ 21.26776   37.05133 ]
 [118.78233  133.01526 ]
 [101.13956  119.13042 ]] 

[[ 81. 101.]
 [103. 119.]
 [ 22.  37.]
 [119. 133.]
 [103. 119.]]


In [20]:
from sklearn import metrics
print('\n Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))


 Mean Squared Error: 0.8854168
