#Task2: Try Linear regression on same prediction data using Tensorflow

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70],[73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70]], dtype='float64')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], 
                    [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float64')

In [3]:
inputs = tf.Variable(inputs)
targets = tf.Variable(targets)
print("targets :\n",targets)

targets :
 <tf.Variable 'Variable:0' shape=(15, 2) dtype=float64, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]])>


In [4]:
v = np.random.rand(3,2)
r = np.random.randn(2)
v = tf.Variable(v)
r = tf.Variable(r)

print(v)
print("\n",r)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[0.88785084, 0.09954326],
       [0.91800928, 0.12553031],
       [0.47454029, 0.21645185]])>

 <tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([-0.00866155,  1.44660058])>


In [5]:
def model(s):
    return s @ v + r

In [6]:
prediction = model(inputs)
print(prediction)

tf.Tensor(
[[146.71630347  26.43121893]
 [191.94115941  35.40462298]
 [227.77094111  39.48213296]
 [147.58451328  25.00653506]
 [182.59975699  35.51762478]
 [146.71630347  26.43121893]
 [191.94115941  35.40462298]
 [227.77094111  39.48213296]
 [147.58451328  25.00653506]
 [182.59975699  35.51762478]
 [146.71630347  26.43121893]
 [191.94115941  35.40462298]
 [227.77094111  39.48213296]
 [147.58451328  25.00653506]
 [182.59975699  35.51762478]], shape=(15, 2), dtype=float64)


In [7]:
def mse(t1,t2):
    return tf.reduce_mean(tf.square(t1 - t2))
print(mse(prediction,targets))

tf.Tensor(7653.583128717583, shape=(), dtype=float64)


In [8]:
epochs = 40
for epoch_count in range(epochs):
    
    with tf.GradientTape(persistent=True) as t:
        current_loss = mse(targets, model(inputs))

    v1 = t.gradient(current_loss,v)
    r1 = t.gradient(current_loss,r)

    v.assign_sub(1e-4 * v1)
    r.assign_sub(1e-4 * r1)
        
    print(f" \n Epoch count: {epoch_count} \n Loss value: {current_loss.numpy()}")


 
 Epoch count: 0 
 Loss value: 7653.583128717583
 
 Epoch count: 1 
 Loss value: 4917.764726519949
 
 Epoch count: 2 
 Loss value: 3191.1767412871286
 
 Epoch count: 3 
 Loss value: 2097.792781342899
 
 Epoch count: 4 
 Loss value: 1402.1476189806122
 
 Epoch count: 5 
 Loss value: 956.7380744746654
 
 Epoch count: 6 
 Loss value: 669.1138413684491
 
 Epoch count: 7 
 Loss value: 481.28667438572506
 
 Epoch count: 8 
 Loss value: 356.8462591446959
 
 Epoch count: 9 
 Loss value: 272.89767008159305
 
 Epoch count: 10 
 Loss value: 215.0154744921262
 
 Epoch count: 11 
 Loss value: 174.08528383751593
 
 Epoch count: 12 
 Loss value: 144.3262999274363
 
 Epoch count: 13 
 Loss value: 122.0528757770041
 
 Epoch count: 14 
 Loss value: 104.8985669126052
 
 Epoch count: 15 
 Loss value: 91.32966034013938
 
 Epoch count: 16 
 Loss value: 80.33992722463304
 
 Epoch count: 17 
 Loss value: 71.25886038651576
 
 Epoch count: 18 
 Loss value: 63.63100569694883
 
 Epoch count: 19 
 Loss value: 57.